/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['[_nghost-%COMP%] {\n	position: relative;\n	display: block;\n	left: 0;\n	right: 0;\n	height: 100%;\n}\n\n.gridster-container[_ngcontent-%COMP%] {\n	position: relative;\n	height: 100%;\n	list-style: none;\n  \n	-webkit-transition: width 0.2s,\n height 0.2s;\n	transition: width 0.2s,\n height 0.2s;\n}\n\n.position-highlight[_ngcontent-%COMP%] {\n	display: block;\n	position: absolute;\n	z-index: 1;\n}\n\n.position-highlight[_ngcontent-%COMP%]   .inner[_ngcontent-%COMP%] {\n	position: absolute;\n	background-color: #768294;\n	border: 1px solid transparent;\n	top: 0;\n	bottom: 10px;\n	left: 10px;\n	right: 0;\n	-webkit-transition: background 3s;\n	transition: background 3s;\n	border-radius: 3px;\n	box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);\n}'];