/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['[_nghost-%COMP%] {\n	display: block;\n	position: absolute;\n	top: 0;\n	left: 0;\n	z-index: 1;\n	cursor: pointer;\n	-webkit-transition: top 0.2s,\n left 0.2s,\n width 0.2s,\n height 0.2s,\n font-size 0.2s,\n line-height 0.2s;\n	transition: top 0.2s,\n left 0.2s,\n width 0.2s,\n height 0.2s,\n font-size 0.2s,\n line-height 0.2s;\n}\n\n.is-dragging[_nghost-%COMP%] {\n	-webkit-transition: none;\n	transition: none;\n	z-index: 9999;\n}\n\n.is-dragging[_nghost-%COMP%]   .gridster-item-inner[_ngcontent-%COMP%] {\n	box-shadow: 0 2px 6px rgba(0, 0, 0, 0.24), 0 2px 4px rgba(0, 0, 0, 0.48);\n	top: -3px;\n	bottom: 13px;\n}\n\n[_nghost-%COMP%]   .gridster-item-inner[_ngcontent-%COMP%] {\n	position: absolute;\n	background: #fff;\n	border: 1px solid transparent;\n	top: 0;\n	bottom: 10px;\n	left: 10px;\n	right: 0;\n	overflow: auto;\n	-webkit-transition: background 3s;\n	transition: background 3s;\n	border-radius: 3px;\n	box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);\n}'];